---
- name: Create bringup service (placeholder)
  copy:
    dest: /etc/systemd/system/rover-bringup.service
    content: |
      [Unit]
      Description=Rover bringup
      After=network.target

      [Service]
      Type=simple
      User=alpha_viam
      ExecStart=/usr/bin/bash -lc 'source /opt/ros/humble/setup.bash && \
      ros2 launch alpha_viam_bringup base_bringup.launch.py'
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
  notify: Reload systemd
