<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="alpha_viam_rover">
  <!-- Minimal URDF/Xacro for TF and diff-drive semantics. Dimensions are placeholders. -->

  <!-- Parameters -->
  <xacro:property name="wheel_separation" value="0.30"/>
  <xacro:property name="wheel_radius" value="0.06"/>

  <!-- Base with simple geometry/inertial -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="2.0"/>
      <inertia ixx="0.02" ixy="0.0" ixz="0.0" iyy="0.02" iyz="0.0" izz="0.04"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <box size="0.25 0.18 0.10"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <box size="0.25 0.18 0.10"/>
      </geometry>
    </collision>
  </link>

  <!-- Wheels -->
  <link name="left_wheel_link"/>
  <link name="right_wheel_link"/>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0 ${wheel_separation/2.0} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0 ${-wheel_separation/2.0} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Sensors -->
  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
  </joint>

  <link name="lidar_link"/>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.10 0 0.08" rpy="0 0 0"/>
  </joint>

  <!-- ros2_control: system + joint interfaces (placeholders for real hardware) -->
  <ros2_control name="RoverSystem" type="system">
    <hardware>
      <plugin>l298n_hardware/L298NSystemHardware</plugin>
      <!-- L298N pin map (BCM numbering) and encoder pins -->
      <param name="left_pwm">26</param>
      <param name="left_in1">19</param>
      <param name="left_in2">13</param>
      <param name="right_pwm">22</param>
      <param name="right_in3">6</param>
      <param name="right_in4">5</param>
      <!-- Encoders: set to your GPIOs or -1 to disable -->
      <param name="left_enc_a">-1</param>
      <param name="left_enc_b">-1</param>
      <param name="right_enc_a">-1</param>
      <param name="right_enc_b">-1</param>
      <!-- Encoder + control params -->
      <param name="ticks_per_rev">20</param>
      <param name="encoder_glitch_us">100</param>
      <param name="max_wheel_rad_s">20.0</param>
      <param name="pwm_freq">20000</param>
      <param name="pwm_range">255</param>
      <param name="deadband_rad_s">0.10</param>
      <param name="slew_duty_per_s">200.0</param>
      <param name="invert_left">false</param>
      <param name="invert_right">false</param>
      <param name="brake_on_zero">false</param>
      <param name="watchdog_s">0.5</param>
      <param name="debug">true</param>
    </hardware>
    <joint name="left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <!-- Optional transmissions for tooling compatibility (placeholder) -->
  <transmission name="left_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1.0</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="right_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1.0</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
