controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: false

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      # Provide controller parameters at load time (Humble requirement).
      # NOTE: Must be an absolute path; do not rely on CWD.
      params_file: /home/alpha_viam/alpha_viam_rover/configs/diff_drive_params.yaml
