# Diagnostic aggregator minimal config with a catch-all analyzer
diagnostic_aggregator:
  ros__parameters:
    analyzers:
      other:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Other
        startswith: [""]
