ros__parameters:
  left_wheel_names: [left_wheel_joint]
  right_wheel_names: [right_wheel_joint]
  wheel_separation: 0.30
  wheel_radius: 0.06
  publish_rate: 50
  enable_odom_tf: true
  cmd_vel_timeout: 0.5
  odom_frame_id: odom
  base_frame_id: base_link
