# Minimal Nav2 parameters (placeholder, safe defaults)
planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    goal_checker_plugins: ["general_goal_checker"]

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
