# Minimal Nav2 parameters (placeholder, safe defaults)
planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    goal_checker_plugins: ["general_goal_checker"]

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

global_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    plugins: ["static_layer", "inflation_layer"]

local_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 5.0
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05
    plugins: ["voxel_layer", "inflation_layer"]

behavior_server:
  ros__parameters:
    use_sim_time: false
    goal_checker_plugins: ["general_goal_checker"]
